# Generated by Django 5.0.7 on 2024-08-28 18:59

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbluser',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('userid', models.CharField(db_column='UserID', max_length=20, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=128)),
                ('groupname', models.CharField(db_column='GroupName', max_length=30)),
                ('first_name', models.CharField(db_column='FirstName', max_length=50)),
                ('last_name', models.CharField(db_column='LastName', max_length=50)),
                ('addressline1', models.CharField(blank=True, db_column='AddressLine1', max_length=50, null=True)),
                ('addressline2', models.CharField(blank=True, db_column='AddressLine2', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='PostalCode', max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_column='Country', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('fax', models.CharField(blank=True, db_column='Fax', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='EMail', max_length=50, null=True)),
                ('company', models.CharField(db_column='Company', max_length=50)),
                ('is_active', models.BooleanField(blank=True, db_column='Active', null=True)),
                ('contactname2', models.CharField(blank=True, db_column='ContactName2', max_length=50, null=True)),
                ('email2', models.CharField(blank=True, db_column='EMail2', max_length=50, null=True)),
                ('alerts', models.BooleanField(db_column='Alerts')),
                ('defaultzebra', models.IntegerField(blank=True, db_column='defaultZebra', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='LastLoginDate', null=True)),
                ('branchid', models.IntegerField(blank=True, db_column='BranchID', null=True)),
                ('is_superuser', models.BooleanField(blank=True, db_column='isSupervisor', null=True)),
                ('isaccountrep', models.BooleanField(blank=True, db_column='isAccountRep', null=True)),
                ('sendnotification', models.BooleanField(blank=True, db_column='SendNotification', null=True)),
                ('isflex', models.BooleanField(blank=True, db_column='isFlex', null=True)),
                ('customizedoptions', models.BooleanField(blank=True, db_column='CustomizedOptions', null=True)),
                ('iscustomerrelation', models.BooleanField(blank=True, db_column='isCustomerRelation', null=True)),
                ('isfirstloadingrequestassigned', models.BooleanField(blank=True, db_column='isFirstLoadingRequestAssigned', null=True)),
                ('supervisorpin', models.CharField(blank=True, db_column='SupervisorPIN', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tblUser',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='title', max_length=50)),
                ('content', models.CharField(db_column='content', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Note',
                'managed': False,
            },
        ),
    ]
