# Generated by Django 5.0.7 on 2026-07-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsiType',
            fields=[
                ('dsi_type', models.CharField(db_column='DSI_Type', max_length=50)),
                ('dsi_idtype', models.CharField(db_column='DSI_idType', max_length=10)),
                ('dsi_id_type', models.IntegerField(db_column='DSI_id_type', primary_key=True, serialize=False)),
                ('branch_id', models.IntegerField(db_column='BranchID')),
            ],
            options={
                'db_table': 'VwDSI_types',
                'managed': False,
            },
        ),
    ]
