# Generated by Django 5.0.7 on 2026-07-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dsitype'),
    ]

    operations = [
        migrations.CreateModel(
            name='DsiCarrier',
            fields=[
                ('dsi_carrierid', models.IntegerField(db_column='CarrierID', primary_key=True, serialize=False)),
                ('dsi_companyname', models.CharField(db_column='CompanyName', max_length=50)),
                ('dsi_telephonenum', models.CharField(db_column='TelephoneNum', max_length=50)),
                ('dsi_faxnum', models.CharField(db_column='FaxNum', max_length=50)),
                ('dsi_contactname', models.CharField(db_column='ContactName', max_length=50)),
                ('dsi_active', models.BooleanField(db_column='Active', default=True)),
                ('dsi_paqueteria', models.BooleanField(db_column='Paqueteria', default=True)),
                ('dsi_branchid', models.IntegerField(db_column='BranchID')),
            ],
            options={
                'db_table': 'tblCarrier',
                'managed': False,
            },
        ),
    ]
